#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=60
USE_PROCD=1
PROG=/usr/sbin/eqos

parse_device() {
	local cfg="$1"
	local enabled ip download upload comment mac

	config_get_bool enabled "$cfg" "enabled" "1"
	[ "$enabled" -eq "1" ] || return 0

	config_get ip "$cfg" ip
	config_get download "$cfg" "download" "0"
	config_get upload "$cfg" "upload" "0"
	config_get comment "$cfg" "comment" "32"
	config_get mac "$cfg" "mac"

	$PROG add "$ip" "$download" "$upload" "$comment" "$mac"
}

start_service() {
	config_load "eqos"

	local enabled download upload ipv6enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1

	config_get download "config" "download" "900"
	config_get upload "config" "upload" "90"
	config_get_bool ipv6enabled "config" "ipv6enabled" "0"

	$PROG start "$download" "$upload"

	if [ "$ipv6enabled" -eq "0" ]; then
		ip6tables -t mangle -D FORWARD -j eqos 2>/dev/null
		ebtables -t nat -D POSTROUTING -j eqos -p ipv6 2>/dev/null
	fi

	sleep 1
	config_foreach parse_device "device"
}

stop_service() {
	[ -x "$PROG" ] && $PROG stop
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "eqos"
	procd_add_network_trigger "lan"
}
