name: Build Firmware AX6000 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: FirelightFlagboy/gh-runner-free-disk-space@main

      - name: Initialization environment
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq upgrade
          sudo -E apt-get -yqq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang \
          cmake cpio curl device-tree-compiler dos2unix ecj fastjar flex g++-multilib gawk gcc-multilib gettext git gnutls-dev gperf haveged \
          help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
          libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build \
          p7zip p7zip-full patch pkgconf python3 python3-docutils python3-pip python3-ply python3-pyelftools qemu-utils re2c rsync scons \
          squashfs-tools subversion swig texinfo uglifyjs unzip upx-ucl vim wget xmlto xxd zlib1g-dev zstd
          sudo -E apt-get -yqq autoremove
          sudo -E apt-get -yqq autoclean
          sudo -E apt-get -yqq clean
          sudo -E systemctl daemon-reload

      - name: Prepare
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a
          cp -f defconfig/mt7986-ax6000.config .config

      - name: Build
        run: |
          make defconfig -j$(nproc)
          make download -j$(nproc)
          chmod +x scripts/update.sh
          ./scripts/update.sh
          make -j$(nproc) || make -j1 V=s
          rm -rf ./bin/packages
          rm -rf ./bin/targets/mediatek/mt7986/packages

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Redmi_AX6000
          path: bin/targets/mediatek/mt7986/

      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 1
          gh_token: ${{secrets.GITHUB_TOKEN}}
